# Generated by Django 4.2.7 on 2025-03-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature_dish',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
